# Generated by Django 2.2.4 on 2022-10-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfarepal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Certificate',
            field=models.FileField(upload_to=''),
        ),
    ]
