# Generated by Django 2.2.4 on 2022-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfarepal', '0002_auto_20221011_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DateTimeField(),
        ),
    ]
